[package]
name = "syntax"
version = "0.1.0"
authors = ["agatan <agatan039@gmail.com>"]

[lib]
name = "syntax"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
combine = "~1.3.0"
combine-language = "~0.9.0"
